name: 'Recent Approval Action'
description: 'Fetches the commit with the most recent status'
inputs:
  status:
    description: 'The requested status of commit ("APPROVED", "DISMISSED")'
    required: true
outputs:
  sha:
    description: 'The sha of the found commit; null if not found'
runs:
  using: 'node16'
  main: 'index.js'
