name: GitHub Actions Demo
on:
  pull_request:
    types: [synchronize]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.pull_request.state }}"

