on:
  pull_request:
name: Test
jobs:
  test-workflow:
    name: "test with multiple statuses"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get the commit sha of the most recent review with requested status.
        uses: ./
        id: recent-status
        with:
          status: DISMISSED, APPROVED
          pull-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo
        run: |
          echo ${{ steps.recent-status.outputs.sha }}
          echo ${{ steps.recent-status.outputs.username }}
          echo ${{ steps.recent-status.outputs.date }}
